#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔨 Running build..."
npm run build

if [ $? -ne 0 ]; then
  echo "❌ Build failed. Aborting commit."
  exit 1
fi

echo "Running lint-staged..."
npx lint-staged

if [ $? -ne 0 ]; then
  echo "❌ Lint failed. Aborting commit."
  exit 1
fi

echo "Running tests..."
npm run test

if [ $? -ne 0 ]; then
  echo "❌ Tests failed. Aborting commit."
  exit 1
fi